name: Build php runtime

on:
  push:
    tags:
      - "*"
    paths:
      - ./github/workflows/build-php-runtime.yaml

jobs:
  build:
    name: Build and push php-runtime multiarch images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build arm64 additionaly and push multiarch image to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: "php-runtime/"
          push: true
          tags: "${{ steps.image.outputs.NAME }}"
          platforms: linux/amd64,linux/arm64
